"""empty message

Revision ID: 753ac14ca2bd
Revises: 204a9cf801d1
Create Date: 2022-05-03 20:37:36.833562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753ac14ca2bd'
down_revision = '204a9cf801d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaderboard', sa.Column('last_submit', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaderboard', 'last_submit')
    # ### end Alembic commands ###
